const actionTypes = {
	CREATE_ARTICLE : 'CREATE_ARTICLE',
	CREATE_ARTICLE_BEGIN : 'CREATE_ARTICLE_BEGIN',
	CREATE_ARTICLE_SUCCESS : 'CREATE_ARTICLE_SUCCESS',
	CREATE_ARTICLE_FAILURE : 'CREATE_ARTICLE_FAILURE',
	FETCH_ARTICLE : 'FETCH_ARTICLE',
	FETCH_ARTICLE_BEGIN : 'FETCH_ARTICLE_BEGIN',
	FETCH_ARTICLE_SUCCESS : 'FETCH_ARTICLE_SUCCESS',
	FETCH_ARTICLE_FAILURE : 'FETCH_ARTICLE_FAILURE',
	FETCH_ALL_ARTICLES : 'FETCH_ALL_ARTICLES',
	FETCH_ALL_ARTICLES_BEGIN : 'FETCH_ALL_ARTICLES_BEGIN',
	FETCH_ALL_ARTICLES_SUCCESS : 'FETCH_ALL_ARTICLES_SUCCESS',
	FETCH_ALL_ARTICLES_FAILURE : 'FETCH_ALL_ARTICLES_FAILURE',
	DELETE_ARTICLE : 'DELETE_ARTICLE',
	DELETE_ARTICLE_BEGIN : 'DELETE_ARTICLE_BEGIN',
	DELETE_ARTICLE_SUCCESS : 'DELETE_ARTICLE_SUCCESS',
	DELETE_ARTICLE_FAILURE : 'DELETE_ARTICLE_FAILURE'
};

export default actionTypes;
